FROM osgeo/gdal:ubuntu-small-3.0.2

WORKDIR /app

RUN apt-get update
RUN apt-get -y install python3
RUN apt-get -y install python3-pip

COPY requirements.txt .
RUN pip3 install -r requirements.txt
RUN rm requirements.txt

COPY requirements-dev.txt .
RUN pip3 install -r requirements-dev.txt
RUN rm requirements-dev.txt

ENV PYTHONPATH "${PYTHONPATH}:/app/hsextract"

ENTRYPOINT ["pytest", "tests", "-vv"]