version: '3.4'

services:
  hsextract:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_S3_ENDPOINT=endpoint
    volumes:
      - ./hsextract:/app/hsextract
      - ./hsextract_dbos:/app/hsextract_dbos
      - ./tests:/app/tests
      - ./dbos-tests:/app/dbos-tests