FROM osgeo/gdal:ubuntu-small-3.5.2

WORKDIR /app

RUN apt-get update
RUN apt-get -y install python3.9
RUN apt-get -y install python3-pip
RUN apt-get -y install git

RUN pip3 install -U setuptools
RUN pip3 install -U h5py
RUN pip3 install -U hdf5plugin
RUN pip3 install -U numpy
RUN pip3 install -U netCDF4

COPY requirements.txt .
RUN pip3 install -r requirements.txt
RUN rm requirements.txt

COPY requirements-dev.txt .
RUN pip3 install -r requirements-dev.txt
RUN rm requirements-dev.txt
# Pull in a patch of hsmodels that has the correct field types
RUN pip3 install -U git+https://github.com/hydroshare/hsmodels.git@fea52c68e6dfb7ee470a443d9caef29bba23619e#egg=hsmodels

ENV PYTHONPATH "${PYTHONPATH}:/app/hsextract"

ENTRYPOINT ["pytest", "tests", "-vv"]