apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: metadata-extractor-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      Examines a bucket and extracts metadata
spec:
  entrypoint: metadata-extractor
  templates:
  - name: metadata-extractor
    container:
      image: scootna/hsextract:0.1
      securityContext:
        privileged: true
      env:
        - name: S3_BUCKET
          value: "testbucket"
        - name: MINIO_KEY
          value: "WfnTVHEZjXY8ABz2"
        - name: MINIO_SECRET_KEY
          value: "WdFEIE3g21iSPu56nhfXTgSu4C6fEE7H"
        - name: MNT_POINT
          value: s3